name: Check for GitHub Actions updates

on:
    push:
    schedule:
        # Runs at 04:00 UTC on Mondays and Wednesday
        -   cron: "0 4 * * 1"

jobs:
  gha-updates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Check action updates
      uses: rahulinux/gh-check-action@v1.0.0
